### ISSUE TITLE
Maybe use game controller instead of gc

### ISSUE THREAD

**Issue by Flova** [ros-sports/game_controller_spl#77]
As I am porting the humanoid game controller client I noticed that gc is used frequently in this repo. While I am fine with abbreviations, I think it might make sense to spell it as game controller in the repo/package name and output topic. This makes the purpose more clear, if somebody is looking around and does not click on the repo or just sees the topic.

**Comment by ijnek** [comment]
I do understand your point of "gc" not being self explanatory. I think it would be nice to keep it somewhat consistent between the leagues too. I suggest ``game_controller_spl`` and ``game_controller_hl``. What are your thoughts?

**Comment by Flova** [comment]
@ijnek Do we want to rename the repo? The old link is still a valid forward afaik..

**Comment by ijnek** [comment]
Just updated :+1:

**Comment by ijnek** [comment]
I still need to update the entries in rosdistro to match the new name, will look into doing that.
